language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_packages:
  - covr
  
install:
  - R -e 'install.packages("BiocManager", repos = "https://cloud.r-project.org")'
  - R -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
  - R -e 'install.packages("testthat", repos = "https://cloud.r-project.org")'
  - R -e 'install.packages("shinytest", repos = "https://cloud.r-project.org")'
  - R -e 'BiocManager::install("remotes", ask = FALSE)'
  - R -e 'BiocManager::install("dgkf/scriptgloss", update = TRUE, ask = FALSE)'

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
