language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_packages:
  - BiocManager
  - covr
  
install:
  - R -e 'install.packages("BiocManager"); BiocManager::install("dgkf/scriptgloss", update = TRUE, ask = FALSE);'

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
